---
language: go
go:
  - "1.11"
# disabled due to go dep not being supported on travis
#  - "1.10"

services:
  - redis-server

env:
  - REDIS_VERSION=stable

script:
  - go test -v -race ./...

after_failure:
  - tail -n100 ./*.log
